[project]
name = "fe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "joblib>=1.5.2",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "pymysql>=1.1.2",
    "scikit-learn>=1.7.2",
    "xgboost>=3.1.2",
]
